# Generated by Django 5.1.4 on 2025-04-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0006_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
    ]
